### ISSUE TITLE
PayPal requires a return URL scheme

### ISSUE THREAD

**Issue by kobecarter** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#19]
I have an issue with IOS, I registered the URL types and updated my AppDelegate but still getting the same error 

`[BraintreeSDK] CRITICAL PayPal requires a return URL scheme to be configured via [BTAppSwitch setReturnURLScheme:]. This custom URL scheme must also be registered with your app.`
Here is some screenshots
![Capture d'écran 2019-11-09 17 44 53](https://user-images.githubusercontent.com/53197505/68532269-8e9ee600-031b-11ea-8ab2-f6e9792d3122.png)
![Capture d'écran 2019-11-09 17 46 57](https://user-images.githubusercontent.com/53197505/68532270-8e9ee600-031b-11ea-9a66-86d76cf8463f.png)

**Comment by jameshp** [comment]
Hi,
I'm not sure, but i think you need to call [BTAppSwitch setReturnURLScheme:
@"uk.co.eliascleaners.london.app.paypal"];
in the application:didFinishLaunchingWithOptions:
just after [GeneratedPluginRegistrant registerWithRegistry:self]; and
before you return.
Currently I think this is not even called as it looks to me.

Otherwise:
Did you check everything described here
https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4 ?
e.g.
- if you have configured multiple app targets, you'll have the url to each
of them.
- tested the url in the browser
- double check your apps bundle-id is *uk.co.eliascleaners.london.app*
